### PR TITLE
Add basic uploading via AJAX

### PR DESCRIPTION
**Pull request by cbrulak**
Add a basic AJAX upload call so that the message and canvas are uploaded to a server. 

You need to provide a url (right now it is URL). 

let me know what else I can do :) 

Thanks
Chris

### CODE REVIEW

**Comment by cbrulak** [comment]
Sorry about the whitespace issues, I'll see what I can do to fix it.

**Comment by cbrulak** [comment]
Ok, now it is fixed.

**Comment by niklasvh** [comment]
Nice one! I'm reworking the data gathering steps, making the forms customizable/ability to add multiple phases into the feedback process, and will merge this into it once I finish the restructuring.

**Comment by cbrulak** [comment]
Sounds good. 

let me know if you need any help. This is awesome.  Quite a few impressed people here.

**Comment by niklasvh** [comment]
This commit should provide all the functionality to send the form as well:
https://github.com/niklasvh/feedback.js/commit/f4a5782663eef696b24ff8b1ef6b161b1a67e14f

Still some IE bugs to fix and some more options on highlighting / blackout I want to get sorted, but its a start

**Pull request closed without merging**
